/****************************************************************************
*   Generated by ACUITY 6.30.0
*   Match ovxlib 1.1.83
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_H_
#define _VNN_POST_PROCESS_H_

#include "my_struct.h"

vsi_status vnn_PostProcessKwsModel(vsi_nn_graph_t *graph);

vsi_status vnn_PostProcessVoiceprintUint8(vsi_nn_graph_t *graph, Voiceprint_feature *result);

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

uint32_t vnn_GetPostProcessMapCount();

#endif